import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Image
          src="/profil.jpg"
          alt="My Profile"
          width={200}
          height={200}
          className="m-3 rounded-full mx-auto"
        />
        <h1 className="text-3xl text-center dark:text-white">
          Welcome to My Page
        </h1>
      </main>
    </>
  );
}
