import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faLocationDot,
  faEnvelope,
  faPhone,
} from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Curriculum Vitae</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="bg-gray-100">
        {/* Header */}
        <header className="px-4 py-6 bg-white border-b-2 border-gray-200">
          <div className="container mx-auto">
            <div className="flex">
              <Image
                src="/profil.jpg"
                alt="My Profile"
                width={200}
                height={200}
                className="rounded-full"
              />
              <div className="ml-12">
                <h1 className="text-3xl font-bold text-gray-900">
                  Daniel Budi Prasetyo
                </h1>
                <p className="mt-2 text-xl font-medium text-gray-600">
                  Machine Learning Engineer, Data Analyst, and Web Developer
                  Entusiasm
                </p>
                <div className="mt-4">
                  <p className="text-lg text-gray-800">
                    <FontAwesomeIcon icon={faLocationDot} className="mr-4"/> Dusun Kulon Kali RT
                    04 RW VI
                  </p>
                  <p className="text-lg text-gray-800">
                    <FontAwesomeIcon icon={faEnvelope} className="mr-3"/>{" "}
                    danielbudip789077@gmail.com
                  </p>
                  <p className="text-lg text-gray-800">
                    <FontAwesomeIcon icon={faPhone} className="mr-3"/> +62 81-392-337-207
                  </p>
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* Body */}
        <main className="container mx-auto my-8">
          <div className="flex">
            {/* Left Column */}
            <div className="w-1/3">
              <h2 className="text-2xl font-bold text-gray-900">Education</h2>
              <ul className="list-disc ml-6 mt-4">
                <li className="mb-2">
                  <span className="font-medium">High School:</span> SMAN 1
                  Kudus, 2020
                </li>
                <li className="mb-2">
                  <span className="font-medium">Bachelor Degree:</span> Sanata
                  Dharma University, 2024
                </li>
              </ul>

              <h2 className="text-2xl font-bold text-gray-900 mt-8">Skills</h2>
              <ul className="list-disc ml-6 mt-4">
                <li className="mb-2">Python</li>
                <li className="mb-2">Skill 2</li>
                <li className="mb-2">Skill 3</li>
              </ul>
            </div>

            {/* Right Column */}
            <div className="w-2/3 px-8">
              <h2 className="text-2xl font-bold text-gray-900">
                Work Experience
              </h2>
              <div className="mt-4">
                <h3 className="text-lg font-medium text-gray-700">Job Title</h3>
                <p className="text-gray-800 mt-2">Company Name, Date</p>
                <ul className="list-disc ml-6 mt-4">
                  <li className="mb-2">Responsibility 1</li>
                  <li className="mb-2">Responsibility 2</li>
                  <li className="mb-2">Responsibility 3</li>
                </ul>
              </div>
              <div className="mt-8">
                <h3 className="text-lg font-medium text-gray-700">Job Title</h3>
                <p className="text-gray-800 mt-2">Company Name, Date</p>
                <ul className="list-disc ml-6 mt-4">
                  <li className="mb-2">Responsibility 1</li>
                  <li className="mb-2">Responsibility 2</li>
                  <li className="mb-2">Responsibility 3</li>
                </ul>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
